# wrangler.toml
name = 'key-management-system'
main = "index.js"
compatibility_date = "2025-08-09"

# KV 命名空间配置
[[kv_namespaces]]
binding = "KMS_KV"
id = "KMS_KV"
preview_id = "KMS_KV"

# 定时任务配置 - 每天早上8点检查
[triggers]
crons = ["0 8 * * *"]
