name = "key-managerment-system"
main = "index.js"
compatibility_date = "2025-08-09"
compatibility_flags = ["nodejs_compat"]

# KV 命名空间配置
[[kv_namespaces]]
binding = "KMS_KV"
id = "KMS_KV"

# 定时任务配置 - 每天早上8点检查
[triggers]
crons = ["0 8 * * *"]

# 环境变量（可选，也可以在 Cloudflare Dashboard 中设置）
[vars]
ENVIRONMENT = "production"